### create resource (use generated id for put and get)
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test",
    "number": "1"
}

###
PUT http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: applicaiton/json

{
    "name": "test (updated)",
    "number": "2"
}

###
GET http://localhost:3001/api/persons/