### Create a new note and get its id from response
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "test note",
    "important": true
}

### change the id
DELETE http://localhost:3001/api/notes/64a1dca5eae9fa8eb0d0fc8f

### delete nonexistent note (same as above)
DELETE http://localhost:3001/api/notes/64a1dca5eae9fa8eb0d0fc8f

### delete note with malformatted id
DELETE http://localhost:3001/api/notes/1