### Create a new note and get its id from response
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "test note",
    "important": true
}

### change the id
GET http://localhost:3001/api/notes/64a0dc6d09520d5a3b00f672

### get nonexistent note
GET http://localhost:3001/api/notes/64a0dc6d09520d5a3b90f672

### get note with malformatted id
GET http://localhost:3001/api/notes/1